// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnp3U2FU4x19LRar3fOabJIh9ZTBgbXs8',
    appId: '1:256481551893:web:73ce70901b2e0e788e501c',
    messagingSenderId: '256481551893',
    projectId: 'digitalbrain-237',
    authDomain: 'digitalbrain-237.firebaseapp.com',
    storageBucket: 'digitalbrain-237.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKDdnmPZJGvkNaifyLslAsgSeDYbYam4',
    appId: '1:256481551893:android:d09d003b332c4ad58e501c',
    messagingSenderId: '256481551893',
    projectId: 'digitalbrain-237',
    storageBucket: 'digitalbrain-237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxw7RTeJzqKfLUb4RVF1284Ry2wPF0Uk',
    appId: '1:256481551893:ios:487102feaf795e428e501c',
    messagingSenderId: '256481551893',
    projectId: 'digitalbrain-237',
    storageBucket: 'digitalbrain-237.appspot.com',
    iosBundleId: 'com.example.appFlutter',
  );
}
